FROM ghcr.io/luigi311/encoder-docker-base-image:latest

USER root
WORKDIR /app

# copy the deploy file into the app directory
RUN wget -O FileFlows.zip https://fileflows.com/downloads/zip && \
    unzip FileFlows.zip && \
    rm FileFlows.zip 

COPY ./docker-entrypoint.sh /app/

RUN dos2unix /app/docker-entrypoint.sh && \
    chmod +x /app/docker-entrypoint.sh

# expose the ports we need
EXPOSE 5000

ENTRYPOINT ["/app/docker-entrypoint.sh"]
